version: '3.3'
services:
  mongo:
    build: 
      context: ./MongoDB
    restart: always
    ports:
      - 27017:27017
    volumes:
      - mongodb_data:/data/db
    networks:
      - mongo_net

volumes:
  mongodb_data:

networks:
  mongo_net:
