apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
  labels:
    app: mongodb
spec:
  selector:
    matchLabels:
      app: monodbb
  replicas: 1
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - name: vprodb
        image: rajeshtsdocker/mongodb:V2
        ports:
        - name: mongodb-port
          containerPort: 8081
        env:
         - name: MONGO_INITDB_ROOT_USERNAME
            value: admin
         - name: MONGO_INITDB_ROOT_PASSWORD
           value: Srnaluva6@
        volumeMounts:
          - name: mongo-data
            mountPath: /data/db
      volumes:
        - name: mongo-data
          awsElasticBlockStore:
             volumeID: vol-0e6697157bf6ce091
             fsType: ext4
