apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
  labels:
    app: mongoapp
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
        - name: mongodb
          image: rajeshtsdocker/mongodb:V2
          volumeMounts:
             -mountPath: /data/db
              name: mongodb 
          ports:
            - containerPort: 8081
      nodeSelector:
         zone: us-east-2a
      volumes:
        -name: mongodb
        awsElasticBlockStore:
           volumeID: vol-097b6583ae54ab619
           fsType: ext4     
